/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.goemans.primefinder;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int CountLabel=0x7f050004;
        public static final int GoButton=0x7f050002;
        public static final int LinearLayout01=0x7f050000;
        public static final int LinearLayout02=0x7f050003;
        public static final int LinearLayout03=0x7f050006;
        public static final int PrimeSize=0x7f050005;
        public static final int ResultBox=0x7f050008;
        public static final int ResultLabel=0x7f050007;
        public static final int SearchSpace=0x7f050001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int buttonText=0x7f040002;
        public static final int count_label=0x7f040003;
        public static final int explanation=0x7f040000;
    }
}
